# Debian testing
# image: rocker/r-base:4.1.0
# Ubuntu LTS
# image: rocker/r-ver:4.1.0
# Ubuntu r2u
image: rocker/r2u:22.04
stages:
  - checkrhub
#  - coverage

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  RUN_CI_JOB_AUTO: "false"

default:
  before_script:
    - source inst/prepare_check.sh

check_platforms:
  stage: checkrhub
  script:
    - Rscript inst/rhubcheck.R
  rules:
    - if: $RUN_CI_JOB_AUTO == "false"
      when: manual
