# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker
# Debian testing
image: rocker/r-base
# Ubuntu LTS
#image: rocker/r-ver:4.1.0
stages:
    - test

default:
   before_script:
    - echo "Before script section"
    - mkdir -p installed_deps
    - echo 'R_LIBS="installed_deps"' > .Renviron
    - echo 'R_LIBS_USER="installed_deps"' >> .Renviron
    - echo 'R_LIBS_SITE="installed_deps"' >> .Renviron

test:
   stage: test
   script:
   - echo "Installing system"
   - apt-get update
   - apt-get install --yes libxml2-dev libcurl4-openssl-dev libfontconfig1-dev libssl-dev libfribidi-dev libharfbuzz-dev libfreetype-dev libpng-dev libtiff5-dev libjpeg-dev libprotobuf-dev libjq-dev libgdal-dev libudunits2-dev
   # Minimal packages
   - apt-get install --yes --no-install-recommends r-cran-testthat r-cran-devtools r-cran-dplyr
   - R -e "'devtools' %in% installed.packages()"
   # with recommends and suggests...
   #- apt-get install --yes --install-suggests r-cran-testthat r-cran-devtools
   - apt-get autoremove --yes --purge
   - apt-get autoclean --yes
   #- R -e ".libPaths()"
   #- R -e "install.packages(c(‘usethis’, ‘pkgdown’, ‘rcmdcheck’, ‘roxygen2’, ‘rversions’, ‘urlchecker’), dependencies = TRUE)"
   - R -e "install.packages('devtools', dependencies = TRUE)"
   - R -e "devtools::install_deps(dependencies = TRUE)"
   - echo "Building package"
   - R CMD build . --no-build-vignettes --no-manual
   - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
   - echo "Running check"
   - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
   cache:
      key: "$CI_COMMIT_REF_SLUG"
      paths:
      - installed_deps/
   artifacts:
    paths:
    - '*.Rcheck/'
   only:
   - main

