
on: workflow_dispatch
#  push:
#    branches: [main, dev-options]
#  pull_request:
#    branches: [main, master]

name: One-platform-check

permissions:
  actions: write
  checks: write
  issues: write
  contents: read
  statuses: read

jobs:
  One-platform-check:
    runs-on: ubuntu-latest

    name: One platform check
    
    secrets:
      clientid: ${{ secrets.SCIHUB_CLIENTID }}
      secret: ${{ secrets.SCIHUB_SECRET }}
    
    strategy:
      fail-fast: false

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
